/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type PullQuote = {
  _type: "pullQuote";
  text?: string;
  attribution?: string;
};

export type Callout = {
  _type: "callout";
  tone?: "note" | "warning" | "tip";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type InlineImage = {
  _type: "inlineImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type CodeBlock = {
  _type: "codeBlock";
  language?: string;
  filename?: string;
  code?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  accent?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & CodeBlock)
    | ({
        _key: string;
      } & InlineImage)
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & PullQuote)
  >;
  publishedAt?: string;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PullQuote
  | Callout
  | SanityImageAssetReference
  | InlineImage
  | CodeBlock
  | Tag
  | Slug
  | TagReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: latestPostsQuery
// Query: *[_type == "post" && defined(publishedAt) && publishedAt <= now()]    | order(publishedAt desc)[0...$limit] {      _id,  _updatedAt,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  "tags": tags[]->{ _id, name, "slug": slug.current, accent }  }
export type LatestPostsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    accent: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(publishedAt) && publishedAt <= now()]    | order(publishedAt desc) {      _id,  _updatedAt,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  "tags": tags[]->{ _id, name, "slug": slug.current, accent }  }
export type AllPostsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    accent: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {      _id,  _updatedAt,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  "tags": tags[]->{ _id, name, "slug": slug.current, accent },    seo,    body[]{      ...,      _type == "inlineImage" => { ..., asset-> },      markDefs[]{ ... }    }  }
export type PostBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    accent: string | null;
  }> | null;
  seo: {
    title?: string;
    description?: string;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone?: "note" | "tip" | "warning";
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "codeBlock";
        language?: string;
        filename?: string;
        code?: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "inlineImage";
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "pullQuote";
        text?: string;
        attribution?: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: postsByTagQuery
// Query: *[_type == "post" && defined(publishedAt) && publishedAt <= now()    && $tagSlug in tags[]->slug.current]    | order(publishedAt desc) {      _id,  _updatedAt,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  "tags": tags[]->{ _id, name, "slug": slug.current, accent }  }
export type PostsByTagQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    accent: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: tagBySlugQuery
// Query: *[_type == "tag" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    description,    accent  }
export type TagBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  accent: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: allTagsQuery
// Query: *[_type == "tag"] | order(name asc) {    _id,    name,    "slug": slug.current,    accent,    "postCount": count(*[_type == "post" && references(^._id)      && defined(publishedAt) && publishedAt <= now()])  }
export type AllTagsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  accent: string | null;
  postCount: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allPostSlugsQuery
// Query: *[_type == "post" && defined(publishedAt) && publishedAt <= now()][].slug.current
export type AllPostSlugsQueryResult = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: allTagSlugsQuery
// Query: *[_type == "tag"][].slug.current
export type AllTagSlugsQueryResult = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: sitemapQuery
// Query: {    "posts": *[_type == "post" && defined(publishedAt) && publishedAt <= now()]{      "slug": slug.current,      _updatedAt    },    "tags": *[_type == "tag"]{      "slug": slug.current,      _updatedAt    }  }
export type SitemapQueryResult = {
  posts: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  tags: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(publishedAt) && publishedAt <= now()]\n    | order(publishedAt desc)[0...$limit] {\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  "tags": tags[]->{ _id, name, "slug": slug.current, accent }\n\n  }\n': LatestPostsQueryResult;
    '\n  *[_type == "post" && defined(publishedAt) && publishedAt <= now()]\n    | order(publishedAt desc) {\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  "tags": tags[]->{ _id, name, "slug": slug.current, accent }\n\n  }\n': AllPostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  "tags": tags[]->{ _id, name, "slug": slug.current, accent }\n,\n    seo,\n    body[]{\n      ...,\n      _type == "inlineImage" => { ..., asset-> },\n      markDefs[]{ ... }\n    }\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "post" && defined(publishedAt) && publishedAt <= now()\n    && $tagSlug in tags[]->slug.current]\n    | order(publishedAt desc) {\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  "tags": tags[]->{ _id, name, "slug": slug.current, accent }\n\n  }\n': PostsByTagQueryResult;
    '\n  *[_type == "tag" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    accent\n  }\n': TagBySlugQueryResult;
    '\n  *[_type == "tag"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    accent,\n    "postCount": count(*[_type == "post" && references(^._id)\n      && defined(publishedAt) && publishedAt <= now()])\n  }\n': AllTagsQueryResult;
    '\n  *[_type == "post" && defined(publishedAt) && publishedAt <= now()][].slug.current\n': AllPostSlugsQueryResult;
    '\n  *[_type == "tag"][].slug.current\n': AllTagSlugsQueryResult;
    '\n  {\n    "posts": *[_type == "post" && defined(publishedAt) && publishedAt <= now()]{\n      "slug": slug.current,\n      _updatedAt\n    },\n    "tags": *[_type == "tag"]{\n      "slug": slug.current,\n      _updatedAt\n    }\n  }\n': SitemapQueryResult;
  }
}
